# 
# Report generation script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
proc start_step { step } {
  set stopFile ".stop.rst"
  if {[file isfile .stop.rst]} {
    puts ""
    puts "*** Halting run - EA reset detected ***"
    puts ""
    puts ""
    return -code error
  }
  set beginFile ".$step.begin.rst"
  set platform "$::tcl_platform(platform)"
  set user "$::tcl_platform(user)"
  set pid [pid]
  set host ""
  if { [string equal $platform unix] } {
    if { [info exist ::env(HOSTNAME)] } {
      set host $::env(HOSTNAME)
    }
  } else {
    if { [info exist ::env(COMPUTERNAME)] } {
      set host $::env(COMPUTERNAME)
    }
  }
  set ch [open $beginFile w]
  puts $ch "<?xml version=\"1.0\"?>"
  puts $ch "<ProcessHandle Version=\"1\" Minor=\"0\">"
  puts $ch "    <Process Command=\".planAhead.\" Owner=\"$user\" Host=\"$host\" Pid=\"$pid\">"
  puts $ch "    </Process>"
  puts $ch "</ProcessHandle>"
  close $ch
}

proc end_step { step } {
  set endFile ".$step.end.rst"
  set ch [open $endFile w]
  close $ch
}

proc step_failed { step } {
  set endFile ".$step.error.rst"
  set ch [open $endFile w]
  close $ch
}

set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 

start_step write_bitstream
set ACTIVE_STEP write_bitstream
set rc [catch {
  create_msg_db write_bitstream.pb
  set_param chipscope.maxJobs 3
  set_param xicom.use_bs_reader 1
  open_checkpoint mcs_top_routed.dcp
  set_property webtalk.parent_dir C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.cache/wt [current_project]
  set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
  add_files C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.sdk/hello_world/Debug/hello_world.elf
  set_property SCOPED_TO_REF microblaze_mcs_0 [get_files -all C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.sdk/hello_world/Debug/hello_world.elf]
  set_property SCOPED_TO_CELLS inst/microblaze_I [get_files -all C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.sdk/hello_world/Debug/hello_world.elf]
  catch { write_mem_info -force mcs_top.mmi }
  write_bitstream -force mcs_top.bit 
  catch { write_sysdef -hwdef mcs_top.hwdef -bitfile mcs_top.bit -meminfo mcs_top.mmi -file mcs_top.sysdef }
  catch {write_debug_probes -quiet -force mcs_top}
  catch {file copy -force mcs_top.ltx debug_nets.ltx}
  close_msg_db -file write_bitstream.pb
} RESULT]
if {$rc} {
  step_failed write_bitstream
  return -code error $RESULT
} else {
  end_step write_bitstream
  unset ACTIVE_STEP 
}

