# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config  -id {[BD 41-1306]}  -suppress 
set_msg_config  -id {[BD 41-1271]}  -suppress 
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.cache/wt [current_project]
set_property parent.project_path C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.sdk/hello_world/Debug/hello_world.elf
set_property SCOPED_TO_REF microblaze_mcs_0 [get_files -all C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.sdk/hello_world/Debug/hello_world.elf]
set_property SCOPED_TO_CELLS inst/microblaze_I [get_files -all C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.sdk/hello_world/Debug/hello_world.elf]
read_verilog -library xil_defaultlib {
  C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/new/seven_seg.v
  C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/new/mcs_top.v
}
read_vhdl -library xil_defaultlib C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/new/vga_controller_640_60.vhd
read_ip -quiet C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0.xci
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/microblaze_mcs_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/bd_fc5c_0_microblaze_I_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_1/bd_fc5c_0_rst_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_2/bd_fc5c_0_ilmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_3/bd_fc5c_0_dlmb_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_6/bd_fc5c_0_lmb_bram_I_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_7/bd_fc5c_0_iomodule_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/bd_0/bd_fc5c_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/mb_bootloop_le.elf]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/microblaze_mcs_0/bd_0/ip/ip_0/data/mb_bootloop_le.elf]

read_ip -quiet C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/constrs_1/new/lab4_top.xdc
set_property used_in_implementation false [get_files C:/Users/nhtranngoc/Documents/ECE3829LAB4/project_4/project_4.srcs/constrs_1/new/lab4_top.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top mcs_top -part xc7a35tcpg236-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef mcs_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file mcs_top_utilization_synth.rpt -pb mcs_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
